-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public." job_positions"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.code_accuracy
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying,
    is_verifed boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    first_name character varying,
    last_name character varying,
    nationality_no character varying NOT NULL,
    " year_of_birth" character varying,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    PRIMARY KEY (id)
);

CREATE TABLE public.employees_accuracy
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employees_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company_name character varying,
    web_address character varying,
    " phone_number" character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_accuracy
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employers_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_employess
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying,
    last_name character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_employess_accuracy
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    system_employess_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    password character varying[],
    email character varying[],
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    PRIMARY KEY (id)
);

ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees_accuracy
    ADD FOREIGN KEY (id)
    REFERENCES public.code_accuracy (id)
    NOT VALID;


ALTER TABLE public.employees_accuracy
    ADD FOREIGN KEY (employees_id)
    REFERENCES public.employees (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_accuracy
    ADD FOREIGN KEY (id)
    REFERENCES public.code_accuracy (id)
    NOT VALID;


ALTER TABLE public.employers_accuracy
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.system_employess
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_employess_accuracy
    ADD FOREIGN KEY (system_employess_id)
    REFERENCES public.system_employess (id)
    NOT VALID;

END;